version: "3.8"
services:
    api:
        build:
          context: .
          dockerfile: docker/api/Dockerfile

        restart: always

        env_file:
          - .env
        volumes:
          - .:/usr/src/app
        ports:
          - 5555:5000
        command: [
          "poetry", "run", "uvicorn", "app:create_app",
          "--host", "0.0.0.0",
          "--port", '5000'
        ]
